Use eslint
passwordless/docs pull request #54
Opened 2023-10-03 11:18 UTC by Tyrrrz

This adds ESLint to catch potential errors in our `.vue` and `.js` files.

2023-10-03 11:37 UTC, Tyrrrz commented
Need to merge #51 first

2023-10-03 15:53 UTC, Tyrrrz commented
Something is broken, I'll figure this one out

2023-10-04 10:31 UTC, Tyrrrz commented
Ok @abergs I'm stuck a bit on this one:

<img width="496" alt="image" src="https://github.com/passwordless/docs/assets/1935960/cb8ad4ba-ff4f-4187-a057-746867b5c294">

Where does `Passwordless` come from in this context? It's not imported anywhere.

https://github.com/passwordless/docs/blob/048add2c81a100bd68a27c7ca2ef5ddfff9b3dab/src/.vuepress/components/PasswordlessDemo.vue#L34

2023-10-04 10:38 UTC, Tyrrrz commented
I decided to go with approach 2

2023-10-04 10:39 UTC, Tyrrrz commented
Looks like Cloudflare Pages is failing but I don't have access to the logs to know why

2023-10-04 11:01 UTC, jonashendrickx requested changes

2023-10-04 11:01 UTC, jonashendrickx commented on src/.vuepress/components/PasswordlessDemo.vue
> +    const cached = localStorage.getItem('isPlatformSupporterd');
Looks like a typo
```suggestion
    const cached = localStorage.getItem('isPlatformSupported');
```

2023-10-04 12:00 UTC, abergs commented
Seems you figured it out - LGTM.

Sidenote: we should add that demo button to the docs where it makes sense.

2023-10-04 12:12 UTC, jonashendrickx approved these changes

2023-10-04 12:15 UTC, merged